goldfish_pipe-objs = goldfish_pipe_base.o goldfish_pipe_v1.o goldfish_pipe_v2.o

obj-m += goldfish_pipe.o
obj-m += goldfish_sync.o
obj-m += goldfish_address_space.o
obj-m += goldfish_battery.o

LINUXINCLUDE := -I$(srctree)/../common-modules/virtual-device/uapi ${LINUXINCLUDE}
