#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2023, Arm Ltd
# All rights reserved
#

TASKSET=${TASKSET:-taskset}
LKVM=${LKVM:-lkvm}
ARGS="--realm --irqchip=gicv3 --console=serial --network mode=none --nodefaults"

TESTDIR="."
while getopts "d:" option; do
	case "${option}" in
		d) TESTDIR=${OPTARG};;
		?)
			exit 1
			;;
	esac
done
if [[ ! -d ${TESTDIR} ]]; then
	echo "Invalid directory: ${TESTDIR}"
	exit 1
fi

function run_tests {
	DIR="$1"

	$LKVM run $ARGS -c 2 -m 16 -k $DIR/selftest.flat -p "setup smp=2 mem=16"
	$LKVM run $ARGS -c 1 -m 16 -k $DIR/selftest.flat -p "vectors-kernel"
	$LKVM run $ARGS -c 1 -m 16 -k $DIR/selftest.flat -p "vectors-user"
	$LKVM run $ARGS -c 4 -m 32 -k $DIR/selftest.flat -p "smp"

	$LKVM run $ARGS -c 1 -m 32 -k $DIR/realm-ns-memory.flat

	$LKVM run $ARGS -c 4 -m 32 -k $DIR/psci.flat

	$LKVM run $ARGS -c 4 -m 32 -k $DIR/gic.flat -p "ipi"
	$LKVM run $ARGS -c 4 -m 32 -k $DIR/gic.flat -p "active"

	$LKVM run $ARGS -c 1 -m 16 -k $DIR/timer.flat

	$LKVM run $ARGS -c 1 -m 16 -k $DIR/realm-rsi.flat -p "version"
	$LKVM run $ARGS -c 1 -m 16 -k $DIR/realm-rsi.flat -p "host_call hvc"
	$LKVM run $ARGS -c 1 -m 16 -k $DIR/realm-sea.flat

	$LKVM run $ARGS -c 1 -m 24 -k $DIR/realm-attest.flat -p "attest"
	$LKVM run $ARGS -c 2 -m 24 -k $DIR/realm-attest.flat -p "attest_smp"
	$LKVM run $ARGS -c 1 -m 24 -k $DIR/realm-attest.flat -p "extend"
	$LKVM run $ARGS -c 2 -m 24 -k $DIR/realm-attest.flat -p "extend_smp"
	$LKVM run $ARGS -c 1 -m 24 -k $DIR/realm-attest.flat -p "extend_and_attest"
	$LKVM run $ARGS -c 1 -m 24 -k $DIR/realm-attest.flat -p "measurement"

	$TASKSET -c 0 $LKVM run $ARGS -c 4 -m 32 -k $DIR/realm-fpu.flat
}

run_tests "${TESTDIR}"
