# SPDX-License-Identifier: GPL-2.0

virtio-gpu-objs := virtgpu_drv.o virtgpu_kms.o virtgpu_gem.o virtgpu_vram.o \
	virtgpu_display.o virtgpu_vq.o \
	virtgpu_fence.o virtgpu_object.o virtgpu_debugfs.o virtgpu_plane.o \
	virtgpu_ioctl.o virtgpu_prime.o virtgpu_trace_points.o

obj-m += virtio-gpu.o
LINUXINCLUDE := -I$(srctree)/../common-modules/virtual-device/uapi ${LINUXINCLUDE}
