# SPDX-License-Identifier: GPL-2.0

virtio_snd-objs := \
        virtio_card.o \
        virtio_chmap.o \
        virtio_ctl_msg.o \
        virtio_jack.o \
        virtio_pcm.o \
        virtio_pcm_msg.o \
        virtio_pcm_ops.o

obj-m += virtio_snd.o
LINUXINCLUDE := -I$(srctree)/../common-modules/virtual-device ${LINUXINCLUDE}
